<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Change Password
    </h1>
</section>

<!-- Main content -->
<section class="content">
    <div class="row">
        <!-- left column -->
        <div class="col-md-12">
            <!-- general form elements -->
            <div class="box box-primary">
                <div class="box-header">
                </div><!-- /.box-header -->
                <!-- form start -->
                <form role="form" method="post" name="changepassword" id="changepassword" action="<?php echo $this->url('change'); ?>">
                    <div class="box-body">
                        <div class="form-group">
                            <label for="exampleInputEmail1">Password <span class="error">*</span></label>
                            <input type="password" class="form-control width_20" id="user_password" name="user_password">
                        </div>
                        <div class="form-group">
                            <label for="exampleInputPassword1">Confirm Password <span class="error">*</span></label>
                            <input type="password" class="form-control width_20"  id="conf_user_password" name="conf_user_password">
                        </div>
                    </div><!-- /.box-body -->

                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </form>
            </div><!-- /.box -->
        </div><!-- /.box-body -->
    </div><!-- /.box -->
</section>                 