<!--login modal-->
<div id="loginModal" class="modal show margin-top-30" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">

                <h1 class="text-center">Contributer Login</h1>
            </div>
            <div class="modal-body">
                <form class="form col-md-12 center-block" method="post" name="login" id="login" action="<?php echo $this->url("auth", array("action" => "index")); ?>">
                    <div class="form-group">
                        <input type="hidden" name="token" id="token" class="form-control input-lg" placeholder="Email" value="<?php echo $token; ?>">
                        <input type="text" name="user_email" id="user_email" class="form-control input-lg" placeholder="Email">

                    </div>
                    <div class="form-group">
                        <input type="password" id="user_password" name="user_password" class="form-control input-lg" placeholder="Password">
                    </div>
                    <div class="form-group">
                        <button class="btn btn-primary btn-lg btn-block" type="submit">Sign In</button>

                    </div>
                </form>
            </div>
            <div class="modal-footer" style="border-top:1px solid #fff !important;">
            </div>
        </div>
    </div>
</div>
