<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 ' . $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
              //  ->prependStylesheet($this->basePath() . '/assets/css/style.css')
                ->prependStylesheet($this->basePath() . '/assets/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css')
                ->prependStylesheet($this->basePath() . '/assets/dist/css/AdminLTE.min.css')
                ->prependStylesheet($this->basePath() . '/assets/dist/css/skins/_all-skins.min.css')
                ->prependStylesheet($this->basePath() . '/assets/dist/css/AdminLTE.min.css')
                ->prependStylesheet($this->basePath() . 'assets/css/font-awesome.min.css')
                ->prependStylesheet($this->basePath() . '/assets/bootstrap/css/bootstrap.min.css');
        ?>
        <!-- Scripts -->
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath() . '/assets/dist/js/demo.js')
                ->prependFile($this->basePath() . '/assets/dist/js/pages/dashboard.js')
                ->prependFile($this->basePath() . '/assets/dist/js/app.min.js')
                ->prependFile($this->basePath() . '/assets/bootstrap/js/bootstrap.min.js')
                ->prependFile($this->basePath() . '/assets/plugins/jQuery/jQuery-2.1.4.min.js')
                ->prependFile($this->basePath() . 'assets/js/jquery-ui.min.js')
                ->prependFile($this->basePath() . '/assets/plugins/jQuery/jQuery-2.1.4.min.js')
                ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',));
        ?>

    </head>
    <body class="skin-blue sidebar-mini">
        <div class="wrapper">
            <?php //include('header.phtml'); ?>
            <?php //include('sidebar.phtml'); ?>
            <?php include('messages.phtml'); ?>
            <?php echo $this->content; ?>
            <?php //include('footer.phtml'); ?>
            <?php echo $this->inlineScript() ?>
        </div><!-- ./wrapper -->
    </body>
</html>
