<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-sm-12 margin-top-20">
                <div class="contact-box-old flashmessage wow fadeInLeft">
                    <?php
                    if ($this->flashMessenger()) {
                        echo '<div class="col-lg-12">';
                        // In any of your .phtml files:
                        $flash = $this->flashMessenger();
                        $flash->setMessageOpenFormat('<div%s id="top_space_20">
     <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
         &times;
     </button>
     <ul><li>')
                                ->setMessageSeparatorString('</li><li>')
                                ->setMessageCloseString('</li></ul></div>');

                        echo $flash->render('error', array('alert', 'alert-dismissible', 'alert-danger'));
                        echo $flash->render('info', array('alert', 'alert-dismissible', 'alert-info'));
                        echo $flash->render('default', array('alert', 'alert-dismissible', 'alert-warning'));
                        echo $flash->render('success', array('alert', 'alert-dismissible', 'success-msg-bg'));
                        echo '</div>';
                    }
                    ?>
                </div>
            </div>
        </div>
    </div>